apiVersion: v1
kind: Namespace
metadata:
  name: tenant-core-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: business-analyst-user
  namespace: tenant-core-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-user
  namespace: tenant-core-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: support-user
  namespace: tenant-core-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-user
  namespace: tenant-core-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-owner-user
  namespace: tenant-core-app